### ISSUE TITLE
Regex does not tokenize everything between '\'

### ISSUE THREAD

**Issue by idolaman** [neu5ron/es_stk#1]
Hello!

In the example at README file, when posting:

`POST /es_stk_test/_analyze`
`{`
`    "analyzer": "es_stk_analyzer",`
`    "text": """C:\Users\test\example_binary.exe -exec bypass ^t^e^s^t"""`
`}`

It seems the analyzer did not tokenize the words 'Users' and 'test'.
Is this a bug? or it suppose to be like that? (it happened to me also in other cases)

**Comment by neu5ron** [comment]
This should be resolved. I made the analyzer accurate over "speed". Better support for wildcard now to actually be accurate. It makes more than multiple whitespace a single whitespace and lowercases still.
Thanks for opening an issue. Feel free to report anything else.
